// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/qrcodes/:id": {
    params: {
      "id": string;
    };
  };
  "/qrcodes/:id/scan": {
    params: {
      "id": string;
    };
  };
  "/auth/login": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/qrcodes/:id": {
    params: {
      "id": string;
    };
  };
  "/app/additional": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/webhooks/app/scopes_update" | "/webhooks/app/uninstalled" | "/qrcodes/:id" | "/qrcodes/:id/scan" | "/auth/login" | "/auth/*" | "/app" | "/app/qrcodes/:id" | "/app/additional";
  };
  "routes/webhooks.app.scopes_update.jsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.app.uninstalled.jsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/qrcodes.$id.jsx": {
    id: "routes/qrcodes.$id";
    page: "/qrcodes/:id" | "/qrcodes/:id/scan";
  };
  "routes/qrcodes.$id.scan.jsx": {
    id: "routes/qrcodes.$id.scan";
    page: "/qrcodes/:id/scan";
  };
  "routes/auth.login/route.jsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/auth.$.jsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/_index/route.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/app.jsx": {
    id: "routes/app";
    page: "/app" | "/app/qrcodes/:id" | "/app/additional";
  };
  "routes/app.qrcodes.$id.jsx": {
    id: "routes/app.qrcodes.$id";
    page: "/app/qrcodes/:id";
  };
  "routes/app.additional.jsx": {
    id: "routes/app.additional";
    page: "/app/additional";
  };
  "routes/app._index.jsx": {
    id: "routes/app._index";
    page: "/app";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.jsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.jsx");
  "routes/qrcodes.$id": typeof import("./app/routes/qrcodes.$id.jsx");
  "routes/qrcodes.$id.scan": typeof import("./app/routes/qrcodes.$id.scan.jsx");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.jsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.jsx");
  "routes/_index": typeof import("./app/routes/_index/route.jsx");
  "routes/app": typeof import("./app/routes/app.jsx");
  "routes/app.qrcodes.$id": typeof import("./app/routes/app.qrcodes.$id.jsx");
  "routes/app.additional": typeof import("./app/routes/app.additional.jsx");
  "routes/app._index": typeof import("./app/routes/app._index.jsx");
};